<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <PackageId>Almostengr.Common</PackageId>
    <Company>Robinson Handy and Technology Services LLC</Company>
    <Copyright>Copyright © $([System.DateTime]::UtcNow.ToString(yyyy)) Robinson Handy and Technology Services</Copyright>
    <Product>Almostengr Common Library</Product>
    <Authors>Kenny Robinson</Authors>
    <Description>Common generic classes and methods used for building MVC and Web API applications.</Description>
    <AssemblyName>Almostengr.Common</AssemblyName>
    <RootNamespace>Almostengr.Common</RootNamespace>
    <Version>8.$([System.DateTime]::UtcNow.ToString(yyyy.MM.dd))</Version>
    <PackageReadmeFile>./README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/almostengr/almostengr.common.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/almostengr/almostengr.common</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
  </ItemGroup>
</Project>
