name: Package Release

on:
  push:
    branches:
      - main

jobs:
  package-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      name: Setup .NET Core
      with:
        dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel

    - name: Publish Release
      run: dotnet publish -r linux-arm -c Release -o latestrelease *sln

    - run: mkdir -p release

    - name: Package files in tar
      run: tar -cf release/falconpitwitter.tar latestrelease/*

    - run: rm -rf latestrelease 

    - run: git add fptrelease/

    - run: git config user.name github-actions
    - run: git config user.email github-actions@github.com
    - run: git add fptrelease
    - run: git commit -m "Committed latest release"
    - run: git tag $(dotnet run --project Almostengr.FalconPiTwitter --version)
    - run: git push --tags
    - run: git push
